# Generated by Django 4.0.2 on 2022-04-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.ManyToManyField(help_text='Seleccione su(s) tipo(s) correspondiente(s).', to='pokedex.Type'),
        ),
    ]
